const struct Animation *const dudeguy_anims[] = {
	&dudeguy_anim_walking2,
	&dudeguy_anim_Presenting,
	&dudeguy_anim_talking,
	&dudeguy_anim_idle,
	&dudeguy_anim_stopwalking,
	&dudeguy_anim_typing,
	&dudeguy_anim_phone,
	&dudeguy_anim_shelf,
	&dudeguy_anim_awaiting_response_male,
	&dudeguy_anim_awaiting_response_female,
	&dudeguy_anim_eating,
	&dudeguy_anim_bored,
	&dudeguy_anim_steal_coffee,
	&dudeguy_anim_intro_scene_1,
	NULL,
};
