extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_projector_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_projector_mesh_layer_1_vtx_0[120];
extern Gfx bob_dl_projector_mesh_layer_1_tri_0[];
extern Vtx bob_dl_projector_mesh_layer_1_vtx_1[16];
extern Gfx bob_dl_projector_mesh_layer_1_tri_1[];
extern Vtx bob_dl_room_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_room_mesh_layer_1_vtx_0[8];
extern Gfx bob_dl_room_mesh_layer_1_tri_0[];
extern Vtx bob_dl_room_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_room_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_material1[];
extern Gfx mat_bob_dl_fullbright_white[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_projector_mesh_layer_1[];
extern Gfx bob_dl_room_mesh_layer_1[];
