extern const GeoLayout checkpoint_flag_geo[];
extern u8 checkpoint_flag_mayro_i4[];
extern Vtx checkpoint_flag_checkpoint_flag_mesh_layer_0_vtx_0[10];
extern Gfx checkpoint_flag_checkpoint_flag_mesh_layer_0_tri_0[];
extern Vtx checkpoint_flag_checkpoint_flag_mesh_layer_0_vtx_1[119];
extern Gfx checkpoint_flag_checkpoint_flag_mesh_layer_0_tri_1[];
extern Gfx mat_checkpoint_flag__0mayro_layer0[];
extern Gfx mat_revert_checkpoint_flag__0mayro_layer0[];
extern Gfx mat_checkpoint_flag__1yellow_layer0[];
extern Gfx mat_revert_checkpoint_flag__1yellow_layer0[];
extern Gfx checkpoint_flag_checkpoint_flag_mesh_layer_0[];
