extern const GeoLayout coffee_cup_half_geo[];
extern Vtx coffee_cup_half_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx coffee_cup_half_Cylinder_001_mesh_layer_1_vtx_0[52];
extern Gfx coffee_cup_half_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx coffee_cup_half_Cylinder_001_mesh_layer_1_vtx_1[6];
extern Gfx coffee_cup_half_Cylinder_001_mesh_layer_1_tri_1[];
extern Gfx mat_coffee_cup_half_cup[];
extern Gfx mat_revert_coffee_cup_half_cup[];
extern Gfx mat_coffee_cup_half_coffee_001[];
extern Gfx coffee_cup_half_Cylinder_001_mesh_layer_1[];
